openapi: '3.0.3'
info:
  version: 1.0.0
  title: Greeting API
servers:
  - url: 'http://localhost:3000'
paths:
  /hello:
    get:
      parameters:
        - name: name
          required: false
          schema:
            type: string
          in: query
          description: defaults to World if not given
      operationId: getGreeting
      tags:
        - greeting
      responses:
        200:
          description: returns a greeting
          content:
            application/json:
              schema:
                type: string
